server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/members/**
          filters:
            - StripPrefix=0

        - id: keycloak-service
          uri: lb://keycloak-service
          predicates:
            - Path=/api/v1/keycloak/**
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0

        - id: refund-service
          uri: lb://refund-service
          predicates:
            - Path=/api/v1/refunds/**
          filters:
            - StripPrefix=0

        - id: savings-service
          uri: lb://savings-service
          predicates:
            - Path=/api/v1/epargne/**
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/serenity/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
